version: '3'
services:
  react-app:
    container_name: reactapp
    image: mateuswelter/react:start-arm64 
    ports: 
      - "3001:3000"
    deploy:
      mode: global
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure
        delay: 10s
